name: job-scan

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 9 * * *"  # Every day at 09:00 UTC
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run job scan
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_USE_TLS: "true"
          DEFAULT_KEYWORDS: ${{ secrets.DEFAULT_KEYWORDS }}
          LOCATION_FILTER: ${{ secrets.LOCATION_FILTER }}
          EXCLUDE_SENIOR_TITLES: ${{ secrets.EXCLUDE_SENIOR_TITLES }}
          MAX_YEARS_EXPERIENCE: ${{ secrets.MAX_YEARS_EXPERIENCE }}
        run: |
          python main.py --companies companies.yml


